<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your password_password</name>
   <tag></tag>
   <elementGuidId>ff879a19-c273-4194-aef9-c53811886e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AtWgY5BlTY8hwq4sbhBTr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AtWgY5BlTY8hwq4sbhBTr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b3ab74-6c30-4b45-ab4b-eb44ecca3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>96b74643-c55d-4446-942a-41e9488c0264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0bc8ce83-bcbd-4aa9-8495-fc84f85b51a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0ff5dd7b-bb62-43e5-8d49-e21f7a82105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AtWgY5BlTY8hwq4sbhBTr</value>
      <webElementGuid>f09f86c6-8869-4980-bf85-47d3ecfa1932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>214ba7cf-1e2b-4182-b350-e3a1a1dfef27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>aa7da08e-ed43-48d1-a429-5a7f5dc3bffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8617fafc-b8f2-4be0-8207-3cc5e897f241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c4888a5c-dd4c-4c8b-acac-c06423a68be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kind</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d34cc5a6-9f6f-4bf0-b92e-5264f2635a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZgrjV6RQLZJAJYS05EmF rGCIrXsYYrNCY62raoH5</value>
      <webElementGuid>b5b670fb-bc0f-4922-b4ff-25285886acc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>246d9212-9f91-4d96-a93c-4db8ee668977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AtWgY5BlTY8hwq4sbhBTr&quot;)</value>
      <webElementGuid>10d1d79e-b0e9-4b40-8c2f-93be3f72b121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AtWgY5BlTY8hwq4sbhBTr']</value>
      <webElementGuid>1f4deb94-ee7a-4f24-9a85-c3578bbcfbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/form/div/div[2]/input</value>
      <webElementGuid>e1f2658f-f97d-43ef-9569-48af7b389562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6680365c-7d65-4707-9bf0-11429b23d1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @placeholder = 'password' and @id = 'AtWgY5BlTY8hwq4sbhBTr' and @type = 'password']</value>
      <webElementGuid>48972073-814b-4453-8d08-fd3f48600b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MacSy8Ka7Ul8HUbnxv6Cl']</value>
      <webElementGuid>5c8fed04-6c7f-4fa3-a671-516fa23b6123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @placeholder = 'password' and @id = 'MacSy8Ka7Ul8HUbnxv6Cl' and @type = 'password']</value>
      <webElementGuid>7d948585-917a-4751-b28c-e9c316572f92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
