<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My CalendlyCreate</name>
   <tag></tag>
   <elementGuidId>1c37d8a0-dd0c-4605-af8a-1b75f9014480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.M2jlWzCv8GTSy06Q7q_E._Hgp5Qls5wI2HfjaYPBT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2756f91-6e21-46b2-9210-76d283a4a0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>M2jlWzCv8GTSy06Q7q_E _Hgp5Qls5wI2HfjaYPBT</value>
      <webElementGuid>0ffea501-0ce3-45b9-8590-5709adaea958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My CalendlyCreate</value>
      <webElementGuid>74d4b43b-c79f-4616-a7ca-59bf4e57ce1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bQ_IvAJyMswLH8t9BfyH yohIaPQ8hKIYSUtsEb_W&quot;]/div[@class=&quot;KugZaZLca_qtYXtJk40b ZNeCdjc2mOlTaKHoVdtV&quot;]/main[@class=&quot;e5O3DgXvSgWPoACoTevm zq_pp2IBb5lpS8hhNM2e&quot;]/div[1]/div[@class=&quot;GMwLmrl_fLBhLUXbzW4q Td4h_160kwlAgJdqtHRk&quot;]/div[@class=&quot;_3Ot979ee0nA8tiH0U1N _70Gic_HNRgdVz2iJvRT&quot;]/div[@class=&quot;M2jlWzCv8GTSy06Q7q_E _Hgp5Qls5wI2HfjaYPBT&quot;]</value>
      <webElementGuid>20349e52-036d-42f6-b78d-f2a214493300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/div/div</value>
      <webElementGuid>33f58f15-df32-4030-86dc-1a2a945c9e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::div[4]</value>
      <webElementGuid>91b802b9-d888-4292-940f-571f4f73144d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::div[5]</value>
      <webElementGuid>5a9dd033-1339-4a78-9d97-91a2356cf0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div/div</value>
      <webElementGuid>c76ff799-66ac-42bf-a937-63ce0bac65ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My CalendlyCreate' or . = 'My CalendlyCreate')]</value>
      <webElementGuid>aa5fcf51-f09d-43d0-b582-0e2f6649390f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
