<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Routing_RPgOlicPgNw7243PYNji h0ERjDQ0g0_269698</name>
   <tag></tag>
   <elementGuidId>7027c54f-1f96-48a0-9a9e-676ff5126d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.RPgOlicPgNw7243PYNji.h0ERjDQ0g0VkZNL46c1_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cc01a54-ead6-471a-a2e1-bcb89123b9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RPgOlicPgNw7243PYNji h0ERjDQ0g0VkZNL46c1_</value>
      <webElementGuid>dc548340-e272-4332-8e0f-f9cfd7cccb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bQ_IvAJyMswLH8t9BfyH yohIaPQ8hKIYSUtsEb_W&quot;]/div[@class=&quot;KugZaZLca_qtYXtJk40b ZNeCdjc2mOlTaKHoVdtV&quot;]/main[@class=&quot;e5O3DgXvSgWPoACoTevm zq_pp2IBb5lpS8hhNM2e&quot;]/div[2]/div[@class=&quot;tDhRAV_Mr5iHcWo2ZWYm bCGU8a8O0jMHBmycapKf kjaazBgmXIEKBdlcsCID psF7fTI03fHMrXMb_j8_&quot;]/div[@class=&quot;Q1X31VHgypch04V9vC_T wGbE3zjEJO70bi87TmCI&quot;]/div[1]/div[@class=&quot;RPgOlicPgNw7243PYNji h0ERjDQ0g0VkZNL46c1_&quot;]</value>
      <webElementGuid>9ab8bc5e-9e58-4654-9945-3c7e15385eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div[2]/div/div/div/div</value>
      <webElementGuid>4f9c812e-57a5-42ca-928c-c8818a6b6ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Routing'])[1]/following::div[5]</value>
      <webElementGuid>6f395f89-0f28-4487-86c0-433aa470f327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflows'])[1]/following::div[6]</value>
      <webElementGuid>1c79d71a-44f0-4358-8162-d7b9b0fe835a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Preference Center'])[1]/preceding::div[21]</value>
      <webElementGuid>aa39a7af-8a44-4113-8d58-07f6d431f6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow All'])[1]/preceding::div[23]</value>
      <webElementGuid>2b858d2b-221a-4b33-b13b-2363785bd71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>8a4c64de-27a9-4f9f-afba-a84ae837dd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
