<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In</name>
   <tag></tag>
   <elementGuidId>6ef3d945-f6ee-4f0c-ba17-c6e8a720b944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sc-1phrosk-0.JHvRc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@type='header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d299baab-68e1-4eb8-ac83-7f3ec739f0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>248786d7-c4e3-441e-82f3-b32c42f1f37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>cbfd87fa-49fb-4e18-88eb-7a501d6daba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1phrosk-0 JHvRc</value>
      <webElementGuid>423ec080-8f31-4318-a990-0f4cdac8d0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>114dcda0-d794-4754-b44f-25ec78316e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;right-side-components&quot;)/li[1]/a[@class=&quot;sc-1phrosk-0 JHvRc&quot;]</value>
      <webElementGuid>c26dbfd0-7744-43c1-a8f7-91c7ad979f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@type='header']</value>
      <webElementGuid>5a711192-99fd-464b-9e4b-3e0c788a1a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='right-side-components']/li/a</value>
      <webElementGuid>5a18ea91-e024-4e99-8d70-a33e7d2785c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::a[1]</value>
      <webElementGuid>6c6d6fc6-9351-4453-80a3-5d452ef6006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>a86f95e6-e2fd-4658-883b-bd93d34a00e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get started'])[1]/preceding::a[1]</value>
      <webElementGuid>26b59b48-6e28-4a4b-a464-4ef3c9a1abe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login')])[2]</value>
      <webElementGuid>8985f784-eddf-4ff8-bccf-fe029e569f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>4c085381-055a-44ca-94ed-79dd8b70212c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'header' and @href = '/login' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>08f591b5-a37c-480b-ad52-9d9d5e7cbc6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
