<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in</name>
   <tag></tag>
   <elementGuidId>4d5dd8c4-599a-4a6c-8c57-d3e8f33c5e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-ogknto-0.lIhRd.sc-zyhoqx-0.lqJUX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6506e54-9c23-4ad1-9258-4cec33765d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5195c73-e82d-4ae1-af4e-8697fc034102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>primary-button</value>
      <webElementGuid>cc221cc3-4333-4c29-b139-2ff4b52a3083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mobilelandscape</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>b149e0e9-fd8c-429b-babe-d425fa2600a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5306fd8c-8f31-4a39-8a2e-9384d883a90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ogknto-0 lIhRd sc-zyhoqx-0 lqJUX</value>
      <webElementGuid>092d0757-5c0d-4d34-ab56-74db36930808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>8fa25743-3da1-4f84-9792-371916ed8e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-form&quot;)/div[@class=&quot;sc-1pw04ha-0 flQQOP&quot;]/button[@class=&quot;sc-ogknto-0 lIhRd sc-zyhoqx-0 lqJUX&quot;]</value>
      <webElementGuid>0af0dfaf-3cc3-484d-9208-bd4706a26657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>b76faea6-6396-4fcd-ad1c-4ed1bdaa2696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='email-form']/div[2]/button</value>
      <webElementGuid>05244c19-fcc2-48ff-bbf4-c48622ecb62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendly'])[1]/following::button[1]</value>
      <webElementGuid>c7298a1c-4cf1-4993-91af-bd251ac10a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Don’t have an account?'])[1]/preceding::button[1]</value>
      <webElementGuid>aa801139-ee7f-4326-bd01-b31be4291c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>e6d62de7-1293-4150-b210-e9f8e6c208a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>3404e455-cf62-49a7-a0af-345bd31fd016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
