<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create</name>
   <tag></tag>
   <elementGuidId>3644ee16-1303-4a5f-82f4-0f28c938019d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.flip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Create')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53579eff-874c-4628-a6cd-24b08443fe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flip</value>
      <webElementGuid>47028e69-918a-459c-87ec-625e5d44841f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8e07a5f9-114a-4d23-b112-c2702e4651ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>44b50b0d-f399-44b2-8f30-9eba97c6ccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainWrap&quot;]/div[@class=&quot;whiteboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;rightBar half left&quot;]/div[@class=&quot;create yellow sideNote&quot;]/div[@class=&quot;sectionContent&quot;]/ul[1]/li[1]/a[@class=&quot;flip&quot;]</value>
      <webElementGuid>08c725b4-7def-4f81-90ec-c78a37051883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create')]</value>
      <webElementGuid>38fd2eb7-4af9-4399-bef3-d0037d07904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How'])[1]/following::a[1]</value>
      <webElementGuid>746481dc-9643-4766-a59e-6c5b5e1f96c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share the url'])[1]/preceding::a[1]</value>
      <webElementGuid>ff3ec2a8-f993-4d51-b752-4c00b3e3eb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name *'])[1]/preceding::a[1]</value>
      <webElementGuid>2963bcad-9321-43e0-97ac-ad894f6016e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>e4f6bd42-16d9-4e2f-8406-a0a77c92b7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>7eca892e-b9d3-4e2b-b56d-92ee3a2a7eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a</value>
      <webElementGuid>c55d2638-2d09-4775-8993-9aa30ea6be21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>73b726a8-dec5-4124-b2cb-3b72a5bd7a8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
